### ISSUE TITLE
Meta bug passage dev->master

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#109]
Méta bug pour traquer tout les petits bugs, régressions etc. qui ont été amenée par les gros changement récents.

- [x] régression soustractions poids poubelles https://github.com/mart1ver/oressource/issues/120
- [x] https://github.com/mart1ver/oressource/issues/128 le bouton d'effacement de la page ne remet pas à l'état initial pas le menu d'entreprise de recyclage ni les matériaux voir https://github.com/mart1ver/oressource/pull/137
- [x] #139  Le commentaire ne s’efface pas aux collectes fixé dans #141 
- [x] https://github.com/mart1ver/oressource/issues/135 Le soustracteur de conteneurs de la calculette ne s'affiche pas aux collectes
- [x] bug: https://github.com/mart1ver/oressource/issues/112 fix: https://github.com/mart1ver/oressource/pull/113 Relecture: @darnuria Login cassé si mdp/login faux entré.
- [x] https://github.com/mart1ver/oressource/issues/115
- [x] https://github.com/mart1ver/oressource/issues/123 collecte cassée (pas d'encaissement,pas de  bad request)
- [x] mise en page de la collecte à harmoniser sur les autres formulaires
 - [x] #125 sorties partenaires cassée (pas d'encaissement  bad request)
- [x]  #125 sorties recyclage cassée (pas d'encaissement bad request )
- [x] https://github.com/mart1ver/oressource/issues/136 et #142  toutes sorties
Test des sorties

**Comment by darnuria** [comment]
Petite suggestion on pourra sûrement en profiter pour faire une version avec toutes les modifications que l'on aura faites.

**Comment by mart1ver** [comment]
- [ ] sorties partenaires cassée (pas d'encaissement  bad request)
- [ ] sorties recyclage cassée (pas d'encaissement bad request )
- [ ] sorties Don fonctionnent (pas de bad request ) mais probleme d'insert dans la base...

**Comment by darnuria** [comment]
J'ai ouvert une issue pour le bug sur les types contenant avec une proposition de résolution https://github.com/mart1ver/oressource/issues/135

**Comment by darnuria** [comment]
@mart1ver Tu peux me donner plus d'informations sur  
> Le commentaire ne s’efface pas aux collectes (A confirmer)
Juste en relisant les sources je vois pas trop ou est le soucis je vais quand même tester demain.

**Comment by darnuria** [comment]
> - [x] sorties Don fonctionnent (pas de bad request ) mais probleme d'insert dans la base...
> Test des sorties

Je peux avoir un screnn shot ou un exemple de ce que fait la base pour commencer à chercher demain. :)

**Comment by darnuria** [comment]
J'ai mis à jour les bugs récents reste toujours ce soucis de soustraction des poubelles vais me lancer dedans ce soir. La j'étais dans le jus des projets de la fac. Fiouf ça avance bien la chasse aux bugs ;)
