### ISSUE TITLE
Refonte des ventes GUI/Logique

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#180]
Reprendre ventes.php sur le modèle des collectes et sorties.
Questions fonctionnalités on en est :
Client:
- [x] Saisie d'un « article » avec ou sans objet
- [x] Pavé numérique avec les champs quantités, masse, prix fonctionnel
- [x] Affichage des articles
- [x] Structure de donnée (simple)  représentant les données
- [x] Suppressions d'articles
- [x] Envoie des données au serveur en JSON
- [x] Ventes en lot fonctionnelle voir #232 
- [x] Pesée en caisse voir https://github.com/mart1ver/oressource/issues/131
- [x] Obligation de la pesée en caisse si actif dans les config
- [x] merge https://github.com/mart1ver/oressource/pull/229
- [x] Mise à jour des bilans ventes.

Serveur:
- [x] Point d'API `POST` sur `/api/ventes`
- [x] Pesées associées a des ventes.

Repousse dans une autre issue:
- [ ] Unifié gestion Remboursement/Ventes ~plus tard~ En fait ça fait 300 lignes de front minimum en moins... https://github.com/mart1ver/oressource/issues/288

J'ai malheureusement pas réutiliser tout le code des sorties/collectes car je suis d'accord avec @yvan-sraka j'ai un peu trop fait tordu pour du code qui va bouger.

Édition le 2017-12-26

**Comment by darnuria** [comment]
En lien avec https://github.com/mart1ver/oressource/issues/131
Je fait ça demain et ce sera la dernier gros changement en vue de la 0.2.0.
Je pense.

**Comment by darnuria** [comment]
J'ai une branche la dessus c'est encore très actif j'ai essayé de faire moins plat de pâte sans trop faire d'ingénierie dessus. https://github.com/darnuria/oressource/tree/refactoring/ventes

**Comment by darnuria** [comment]
On pars sur le bug spécifique des remboursements #288 le reste c'est bon!
