### ISSUE TITLE
Faire un script de mise à jour de la DB pour intégrer les changements récents.

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#243]
L'idée assez simple faire un script qui permet de saute d'un ancien schéma au plus récent.

Je propose qu'on propose à @el-dge de faire une PR avec les changements dispo sur https://github.com/LeMondeAllantVers/oressource/tree/dev_script_maj_bd.

Voir:

- [x] #244 Scripts d'upgrade
- [x] #232 Booleen pour ventes par lot dans vendus
- [x] PR #276 Suppression des adhérents
- [x] #150 Transformer les oui/non en bool compatible sql.
- [x] #155 Passer la base de test en UTF-8 comme fait à la roquette.

**Comment by el-dge** [comment]
Les nouveaux modes de fonctionnement par défaut de MySQL et MariaDB ne permettent plus de rien insérer dans une colonne indiquée `NOT NULL` sans valeur par `DEFAULT`.

Il faudrait soit reprendre tous les `INSERT/UPDATE` pour spécifier une valeur dans ces colonnes ou plus facilement changer le schéma de la BD en supprimant tous les `NOT NULL` (bof) ou mieux : ajouter des `DEFAULT 0` par exemple après nos `NOT NULL`.

Je ne connais pas encore assez toute la bd et ses implications pour faire ça sans tout casser !

**Comment by darnuria** [comment]
@el-dge Ça me parait bien d'ajouter des contraintes sérieuses. 
Par défaut on voudra pas avoir forcément `0`. Mais avoir des contraintes en SQL est en généralement une bonne habitude.

Plus que reprendre les `INSERT/UPDATE` utiliser les contraintes de clef et contraintes général me parait plus fiable même si ça rajoute un script SQL à écrire.

**Comment by darnuria** [comment]
@el-dge On à décidé avec martin d'être compatible pour la prochaine version issue de `dev` avec les changements de mysql https://github.com/mart1ver/oressource/issues/270.

**Comment by darnuria** [comment]
Les cas généraux sont géré. N'hésitez pas à ouvrir des issues si on à oublier des cas particuliers.
