### ISSUE TITLE
Test au 22 Septembre 2017

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#248]
Edit: @mart1ver 14 Septembre 2017 mise à jour
Edit: @darnuria 19 Septembre 2017point sur les corrections faites.
Edit: @darnuria 22 Septembre 2017 update sur les résolutions des `bilan*`.

###  Point de collecte: 
- [x] Mise en page parfaite les collectes passent , ça marche avec l'antidate  

### Sorties hors boutique :
- [x] #247 Mise en page qui reprend parfaitement la collecte :+1: 
- [x] #260 #259  sorties poubelle, cassée (un soucis avec numpad.js à priori, php ne crache pas d'erreur):
![poubelles fail](https://user-images.githubusercontent.com/7695290/30429525-2581e5b6-9958-11e7-85c7-78e92f2919d0.png)
- [x] #259 sorties déchetterie, cassée: -> oublié import composants.php
![dechetterie fail](https://user-images.githubusercontent.com/7695290/30429532-292dd9cc-9958-11e7-9d18-971c35615b4c.png)

![dechetterie fail buffer](https://user-images.githubusercontent.com/7695290/30429695-b7508646-9958-11e7-81d3-306409f66132.png)

### Ventes:

- [x] Les ventes passent  :+1:
- https://github.com/mart1ver/oressource/issues/297 Le rendu monnaie semble un peut risqué en bas du ticket en cas de liste d'achat un peut longue,
- [x] La somme due dans le rendu monnaie ne se reset pas à l'encaissement
![reset encaissement deconne](https://user-images.githubusercontent.com/7695290/30379190-f708ebb6-9895-11e7-9800-5e8fc2430b97.png)

 
###  Bilans:
- - [x] #249  Probleme de datepicker 
- - [x] (résolu je pense) Prise en compte de `$GET[;numero'] === 0` sur le bilan des collectes et sur le bilan hors boutiques.
- - [x] #251 Bilanhb
- - [x] #251 #256 Bilanc
- - [x] #263 Bilanv

### Grilles de prix:
- [x] cassé...
![capture du 2017-09-13 15-13-59](https://user-images.githubusercontent.com/7695290/30379286-412250c0-9896-11e7-968a-cce2ecaf7590.png)
